### ISSUE TITLE
About lincense

### ISSUE THREAD

**Issue by TheKK** [mozilla-b2g/mozbench#27]
I think we need to pick up a license for mozbench itself, and figure out if we have permission to put these benchmarks in this repository.

**Comment by dminor** [comment]
Unless there is a reason to do otherwise, I'd suggest we use the MPL.

Existing benchmark licenses:
Massive - MIT
webaudio-padenot - MPL
smoketest - MPL (it is derived from webaudio-padenot)
Kraken - redistribution allowed provided copyright notice is maintained
Chalkboard - no license
Octane - redistribution allowed provided copyright notice is maintained
Unity-WebGL - no license, but the author helped us get it working (see https://bugzilla.mozilla.org/show_bug.cgi?id=1079438#c36)

In the comment on the Unity-WebGL code it sounded like a formal release was going to happen once the code is cleaned up. We should see if that ever happened so we can potentially update to a licensed version.

I don't think Chalkboard provides a lot of value, if we can't find a license for it I'd suggest we just remove it from the repo. If people really care about the results, I can always host it on an internal repo that the benchmark machines can access so at least we're not "distributing" it.
